apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: payment-service
build:
  artifacts:
    - image: food-delivery/payment-service
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: payment-service
        chartPath: ../../deployments/helm/charts/payment-service
        namespace: food-app
        setValues:
          image.repository: food-delivery/payment-service
          image.tag: latest
portForward:
  - resourceType: service
    resourceName: payment-service
    namespace: food-app
    port: 8080
    localPort: 8004
